# -*- coding: utf-8 -*-
"""Cópia_Projeto_SoulCode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/143W-0I3-p9QhRBiY8XXwNKcubJg5NcTi
"""

alf = ['a', 'b', 'c', 'ç', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ', '"', "'", '!', '?', '¹', '²', '³', '£', '@', '#', '$', ',', '%', '¢', '¨', '¬', '&', '*', '(', ')', '-', '_', '=', '+', '§', '´', '`', '[', '{', 'ª', ']', '}', 'º', '^', '~', '/', '°', ':', ';' , ',', 'ü', 'é', 'â', 'ä', 'à', 'å', 'ê', 'ë', 'è', 'ï', 'î', 'ì', 'æ', 'ô', 'ö', 'ò', 'û', 'ù', 'ÿ', 'ø', 'á', 'í', 'ó', 'ú', 'ñ', 'ª', 'º', '¿', '®', '¬', '¡', '«', '»', '_', '_', '_', '¦', '¦', '©', '+', '-', '¢', '¥', 'ã', '¤', 'ð', 'Ð', 'Ê', 'Ë', 'È', 'Í', 'Î', 'Ï', 'Ì', 'ß', 'µ', 'Þ', 'Þ', 'Ú', 'Û', 'Ù', 'ý', '±', '÷']
carrinho = 0
listaDeCompras = []
listaitem = ['Energético TNT', 'Pão de Queijo', 'Água']
listavalores = [4, 3, 2]
gasitem = ['Gasolina', 'Álcool', 'Gás Natural']
gasvalores = [4, 3, 2]
servitem = ['Lavagem', 'Troca de óleo']
servvalores = [15, 50]
pagamentos = ['(1)- Crédito', '(2)- Débito', '(3)- Pix', '(4)- Boleto', '(5)- Dinheiro', '(0)- Voltar']
cedulas = [50, 20, 10, 5, 2, 1]
carteira = 0


print ('--------------------------------------------------------------------------')
print('\tBem vindo(a) ao Posto de Gasolina SoulCode Academy.')
print ('--------------------------------------------------------------------------')
posto = True

while posto:
  ''' MENU PRINCIPAL '''
  entrada = input('\nDigite A para entrar no programa ou F para fechar o programa \n')
  if entrada.upper() == 'A':
      departamentos = True

      while departamentos:
        ''' MENU DEPARTAMENTOS '''
        print ('--------------------------------------------------------------------------')
        print('\n Selecione o departamento desejado:\n')
        depto = input('(1)-Abastecimento \n(2)-Conveniência \n(3)-Serviços \n(9)-Finalizar Compra \n(0)-Cancelar ou Voltar ao menu principal \n(F)-Fechar programa.\n')

        if depto == '1':

          abastecimento = True
          while abastecimento:
            ''' MENU ABASTECIMENTO '''
            print ('--------------------------------------------------------------------------')
            opcao1 = input('Digite a opção desejada: \n(1) Gasolina\t\t\tR$ 4,00/L \n(2) Álcool\t\t\tR$ 3,00/L \n(3) Gás Natural\t\t\tR$ 2,00/L \n(0) Voltar \n')
            
            if opcao1 == '1' or opcao1 == '2' or opcao1 == '3' or opcao1 == '0':
              if opcao1 == '0':
                break
              else:
                tipo = str(input('\nDeseja pagar por quantidade de litros ou valor específico?\n (1)-Dinheiro (2)-Litros\n'))
                if tipo == '1' or tipo == '2':
                  if tipo =='1':
                    while True:
                      con = 0
                      valor = input(f'\nDigite a quantidade de dinheiro inserido.\nR$')
                      valor = valor.lower()
                      for i in valor:
                        if i in alf:
                          con += 1
                      pontos = valor.count(".")
                      if con == 0 and valor[0] != '.' and valor[-1] != '.' and pontos < 2:
                        teste = False
                        break
                      else:
                        print("Não é um número válido.\nDigite um número.\n")
                    valor = float(valor)  
                    if valor <= 0.0:
                      print('Você não adicionou nenhum item no seu carrinho\n')
                    else:
                      opcao1 = int(opcao1)
                      listaDeCompras.append(gasitem[int(opcao1-1)])
                      total = valor/gasvalores[int(opcao1-1)]
                      carrinho += valor
                      print ('--------------------------------------------------------------------------')
                      print ('--------------------------------------------------------------------------')
                      print(f'\nSua lista de produtos e serviços até o momento: {listaDeCompras}')
                      print(f'Total até o momento: R${carrinho}')
                      print ('--------------------------------------------------------------------------')
                      break
                  else:                               # VALOR DE ABASTECIMENTO POR LITRO
                    while True:
                      con = 0
                      valor = input(f'\nDigite a quantidade de litros inserido.\n')
                      valor = valor.lower()
                      for i in valor:
                        if i in alf:
                          con += 1
                      pontos = valor.count(".")
                      if con == 0 and valor[0] != '.' and valor[-1] != '.' and pontos < 2:
                        teste = False
                        break
                      else:
                        print("Não é um número válido.\nDigite um número.\n")
                    valor = float(valor)
                    if valor <= 0.0:
                      print('Você não adicionou nenhum item no seu carrinho\n')
                    else:
                      opcao1 = int(opcao1)
                      listaDeCompras.append(gasitem[int(opcao1-1)])
                      total = valor * gasvalores[int(opcao1-1)]
                      carrinho += total
                      print ('--------------------------------------------------------------------------')
                      print ('--------------------------------------------------------------------------')
                      print(f'\nSua lista de produtos e serviços até o momento: {listaDeCompras}')
                      print(f'Total até o momento: R${carrinho}') 
                      print ('--------------------------------------------------------------------------')     
                else:
                  print('Opção inválida! Digite novamente')
            else:
              opcao1 = input('Opção inválida! Digite novamente\n')

        elif depto == '2':
          conveniencia = True
          while conveniencia:
            ''' MENU COVENIENCIA '''
            print ('--------------------------------------------------------------------------')
            opcao1 = input('Digite a opção desejada: \n(1) Energético TNT\t\t\tR$ 4,00 \n(2) Pão de Queijo\t\t\tR$ 3,00 \n(3) Água\t\t\tR$ 2,00 \n(0)- Voltar \n')
            if opcao1 == '1' or opcao1 == '2' or opcao1 == '3' or opcao1 == '0':
              if opcao1 == '0':
                break
              else:
                while True:
                  con = 0
                  valor = input(f'Digite a quantidade desejada.\n')
                  valor = valor.lower()
                  for i in valor:
                    if i in alf:
                      con += 1
                  pontos = valor.count(".")
                  if con == 0 and valor[0] != '.' and valor[-1] != '.' and pontos == 0:
                    teste = False
                    break
                  else:
                    print("Não é um número válido.\nDigite um número.\n")
                valor = int(valor)
                if valor <= 0:
                  print('Você não adicionou nenhum item no seu carrinho\n')
                else:
                  opcao1 = int(opcao1)
                  listaDeCompras.append(listaitem[int(opcao1-1)])
                  total = valor * listavalores[int(opcao1-1)]
                  carrinho += total
                  print ('--------------------------------------------------------------------------')
                  print ('--------------------------------------------------------------------------')
                  print(f'\nSua lista de produtos e serviços até o momento: {listaDeCompras}')
                  print(f'Total até o momento: R${carrinho}')
                  print ('--------------------------------------------------------------------------')
                  break
            else:
              print('Opção inválida! Digite novamente')
              opcao1 = input('\nDigite a opção desejada: \n(1) Energético TNT\t\t\tR$ 4,00 \n(2) Pão de Queijo\t\t\tR$ 3,00 \n(3) Água\t\t\tR$ 2,00 \n(0)- Voltar \n')

        elif depto == '3':
          servicos = True
          while servicos:
            ''' MENU SERVICOS '''
            print ('--------------------------------------------------------------------------')
            opcao1 = input('(1) Lavagem\t\t\tR$ 15.00 \n(2) Troca de óleo\t\t\tR$ 50.00 \n(0)-Voltar \n')

            if opcao1 == '1' or opcao1 == '2' or opcao1 == '0':
              if opcao1 == '0':
                break
              else:
                while True:
                  con = 0
                  valor = input(f'Digite a quantidade desejada.\n')
                  valor = valor.lower()
                  for i in valor:
                    if i in alf:
                      con += 1
                  pontos = valor.count(".")
                  if con == 0 and valor[0] != '.' and valor[-1] != '.' and pontos == 0:
                    teste = False
                    break
                  else:
                    print("Não é um número válido.\nDigite um número.\n")
                valor = int(valor)
                if valor <= 0:
                  print('Você não adicionou nenhum item no seu carrinho\n')
                else:
                  opcao1 = int(opcao1)
                  listaDeCompras.append(servitem[int(opcao1-1)])
                  total = valor * servvalores[int(opcao1-1)]
                  carrinho += total
                  print ('--------------------------------------------------------------------------')
                  print ('--------------------------------------------------------------------------')
                  print(f'\nSua lista de produtos e serviços até o momento: {listaDeCompras}')
                  print(f'Total gasto até o momento: R${carrinho}')
                  print ('--------------------------------------------------------------------------')
                  break
            else:
              print('Opção inválida! Digite novamente')
              opcao1 = input('(1)-Lavagem-R$ 15.00 \n(2)-Troca de óleo-R$ 50.00 \n(0)-Voltar \n')

        elif depto == '0':
          cancelamento = True
          while cancelamento:
            ''' MENU CANCELAMENTO '''
            print ('--------------------------------------------------------------------------')
            opcao1 = input('Deseja realmente cancelar sua compra? \nCaso desista, seu carrinho será excluído.\n (0)- Não (1)- Sim')

            if opcao1 == '1' or opcao1 == '0':
              if opcao1 == '0':
                break
              else:
                print(f'\nSeus ítens foram excluídos do carrinho')
                departamentos = False
                carrinho = 0
                listaDeCompras = []
                break
            else:
              print('Opção inválida! Digite novamente')

        elif depto =='9':
          finalizacao = True
          while finalizacao:
            ''' MENU FINALIZACAO '''
            print ('--------------------------------------------------------------------------')
            print('Formas de pagamento possíveis: ')
            
            for i in pagamentos:
              print(i)
            opcao1 = input(f'O total da sua compra foi de R$ {carrinho}.\nComo deseja realizar o pagamento?\n')
            ###Lista de compras
            if opcao1 == '1' or opcao1 == '0' or opcao1 =='2' or opcao1 == '3' or opcao1 == '4' or opcao1 == '5':
              if opcao1 =='0':
                break
              elif opcao1 !='5':
                while True:
                  print("Deseja finalizar sua compra?")
                  op = input("Digite (s)-sim (n)-não\n")
                  if op.lower() == 'n':
                    break
                  elif op.lower() == 's':
                    opcao1 = int(opcao1)
                    print ('--------------------------------------------------------------------------')
                    print(f'\nSeus itens foram {listaDeCompras}. \nO valor total para pagamento foi R${carrinho}. \nA forma de pagamento escolhida foi {pagamentos[int(opcao1-1)]}. \nPagamento concluído com sucesso. \nA SouCode Academy agradece a preferência.\n')
                    departamentos = False
                    carrinho = 0
                    listaDeCompras = []
                    break
                  else:
                    print("Não é um opção válida.\nDigite novamente.\n")
              else:
                teste = True
                while True:
                  while teste:
                    con = 0
                    carteira = input(f'Digite a quantidade de dinheiro inserido ou (0) para desistir da compra.\nR$')
                    carteira = carteira.lower()
                    for i in carteira:
                      if i in alf:
                        con += 1
                    pontos = carteira.count(".")
                    if carteira == '0':
                      break
                    elif con == 0 and carteira[0] != '.' and carteira[-1] != '.' and pontos < 2:
                        teste = False
                        break
                    else:
                      print("Não é um número válido.\nDigite um número.\n")

                  troco = float(carteira) - carrinho
                  if troco >= 0:
                    break
                  else:
                    if carteira == '0':
                      break
                    else:  
                      print(f'{carteira} é menor que {carrinho}. É impossível realizar o seu pagamento.\n Insira um valor maior que {carrinho}.')
                      teste = True
                
                if troco == 0:
                  print(f'\nVocê inseriu o valor exato, não gerando troco.\nSeus itens foram {listaDeCompras}. \nO valor total para pagamento foi R${carrinho}. \nA forma de pagamento escolhida foi (5)- Dinheiro. \nPagamento concluído com sucesso. \nA SouCode Academy agradece a preferência.\n')
                  listaDeCompras = []
                  carrinho = 0
                  departamentos = False
                  break
                elif troco > 0:
                  print('--------------------------------------------------------------------------')
                  print(f'Seus itens foram {listaDeCompras}. \nO valor total para pagamento foi R${carrinho}.')
                  print(f'O total do seu troco foi R$ {float(carteira) - carrinho}\n')
                  for cedulas in [50, 20, 10, 5, 2, 1]:    
                    quantidade = troco // cedulas
                    troco = troco % cedulas
                    if quantidade > 0:
                      print(f'Você recebera {int(quantidade)} notas de R$ {cedulas}')
                  print('--------------------------------------------------------------------------')
                  print( 'Pagamento concluído com sucesso. \nA SoulCode Academy agradece a preferência.')
                  print('--------------------------------------------------------------------------')

                  troco = 0
                  carrinho = 0
                  listaDeCompras = []
                  departamentos = False
                  break

        elif depto.upper() == 'F':
          fechar = True
          while fechar:
            departamentos = False
            posto = False
            print ('--------------------------------------------------------------------------')
            print('\t\tPrograma Fechado. \nO \tPosto SoulCode Academy agradece a preferência.')
            print ('--------------------------------------------------------------------------')
            break
        else:
          print("")
          print("Opção inválida!!! tente novamente.")


  elif entrada.upper() == "F":
    print ('--------------------------------------------------------------------------')
    print("\t\t\tObrigado. \n\tO Posto SoulCode Academy agradece a preferência.")
    print ('--------------------------------------------------------------------------')
    break
  else:
    print("Opção inválida!!! tente novamente.")